/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import databases.GraphDB;
import databases.RelationalDB;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class PratoPorAlimentos extends javax.swing.JFrame {

    String selectedInSearch;
    String selectedInAddedList;
    DefaultListModel ingList;

    public PratoPorAlimentos() {
        initComponents();
        this.setTitle("Procurar Pratos por Alimentos");
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        selectedInSearch = null;
        ingList = new DefaultListModel();
        addedIngList.setModel(ingList);
        searchBtn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBtn = new javax.swing.JButton();
        nomeIngInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        addedIngList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        pratosFoundList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        addIngBtn = new javax.swing.JButton();
        removeIngBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBtn.setText("Pesquisar");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Alimento");

        searchList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(searchList);

        addedIngList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addedIngListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addedIngList);

        pratosFoundList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pratosFoundListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(pratosFoundList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText(">");

        jLabel3.setText("Ingredientes");

        jLabel4.setText("Pratos");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        addIngBtn.setText("->");
        addIngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngBtnActionPerformed(evt);
            }
        });

        removeIngBtn.setText("<-");
        removeIngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeIngBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeIngInput))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addIngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeIngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(nomeIngInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(addIngBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeIngBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(resetBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            DefaultListModel listModel = RelationalDB.getAlimentosByName(nomeIngInput.getText());
            searchList.setModel(listModel);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchListMouseClicked
        selectedInSearch = searchList.getSelectedValue();

        if (selectedInSearch == null) {
            return;
        }

        if (evt.getClickCount() == 2) {
            try {
                int id = RelationalDB.getAlimentoID(selectedInSearch);
                AlimentoEdit editForm = new AlimentoEdit(id);
                editForm.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_searchListMouseClicked

    private void addIngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngBtnActionPerformed
        if (selectedInSearch == null) {
            JOptionPane.showMessageDialog(this,
                    "É necessario selecionar um alimento para o poder adicionar há lista de ingredientes!",
                    "Informação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!ingList.contains(selectedInSearch)) {
            ingList.addElement(selectedInSearch);
            fillPratosList();
        }
    }//GEN-LAST:event_addIngBtnActionPerformed

    private void removeIngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeIngBtnActionPerformed
        if (selectedInAddedList == null) {
            JOptionPane.showMessageDialog(this,
                    "É necessario selecionar um ingrediente para o poder remover da lista de ingredientes!",
                    "Informação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ingList.removeElement(selectedInAddedList);
        fillPratosList();
    }//GEN-LAST:event_removeIngBtnActionPerformed

    private void addedIngListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addedIngListMouseClicked
        selectedInAddedList = addedIngList.getSelectedValue();

        if (selectedInAddedList == null) {
            return;
        }

        if (evt.getClickCount() == 2) {
            try {
                int id = RelationalDB.getAlimentoID(selectedInAddedList);
                AlimentoEdit editForm = new AlimentoEdit(id);
                editForm.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_addedIngListMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        nomeIngInput.setText("");
        selectedInSearch = null;
        ingList = new DefaultListModel();
        addedIngList.setModel(ingList);
        pratosFoundList.setModel(new DefaultListModel());
        searchBtn.doClick();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void pratosFoundListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pratosFoundListMouseClicked
        String pratoSelected = pratosFoundList.getSelectedValue();

        if (pratoSelected == null) {
            return;
        }

        if (evt.getClickCount() == 2) {
            try {
                int id = RelationalDB.getPratoID(pratoSelected);
                PratoEdit editForm = new PratoEdit(id);
                editForm.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_pratosFoundListMouseClicked

    private void fillPratosList() {
        if (ingList.getSize() == 0) {
            return;
        }

        List<Integer> ids = new ArrayList<>();
        for (int i = 0; i < ingList.getSize(); i++) {
            String nome = ingList.getElementAt(i).toString();
            try {
                int id = RelationalDB.getAlimentoID(nome);
                ids.add(id);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

        try {
            DefaultListModel listModel = GraphDB.getPratosPorAlimentos(ids);
            pratosFoundList.setModel(listModel);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PratoPorAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PratoPorAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PratoPorAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PratoPorAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PratoPorAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngBtn;
    private javax.swing.JList<String> addedIngList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomeIngInput;
    private javax.swing.JList<String> pratosFoundList;
    private javax.swing.JButton removeIngBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JList<String> searchList;
    // End of variables declaration//GEN-END:variables
}
