/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import databases.DocDB;
import databases.GraphDB;
import databases.RelationalDB;
import entities.Ingrediente;
import entities.Prato;
import entities.PratoNutriInfo;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Andreia Machado
 */
public class TabelaNutricional extends javax.swing.JFrame {
    private int idPrato;
    private JTableHeader header;
    private TableColumn column;

    /**
     * Creates new form TabelaNutricional
     */
    public TabelaNutricional() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tabelaNutricional.setEnabled(false);
    }
    
    public TabelaNutricional(int idPrato) {
        this();
        this.idPrato = idPrato;
        header = tabelaNutricional.getTableHeader();
        column = header.getColumnModel().getColumn(1);
        initializeVaribles();
    }
    
    
    private void initializeVaribles() {
        try {
            Prato prato = RelationalDB.getPrato(idPrato);
            this.setTitle("Tabela Nutricional do "+prato.getNome());
            nomeDoPrato.setText("<html>Nome do Prato: "+prato.getNome()+"</html>");
            Prato pratoDoc = DocDB.getPrato(idPrato);
            cozinhaPrato.setText("Categoria: "+pratoDoc.getCozinha());
            dosesPrato.setText("Doses: "+pratoDoc.getDoses());
            column.setHeaderValue("Por " + pratoDoc.getDoses() + " Doses");
            header.repaint();
            
            List<Ingrediente> listaDeIng = GraphDB.getListIngContidosEmPrato(idPrato);
            PratoNutriInfo pratoInfo = RelationalDB.getPratoNutriInfo(listaDeIng);
            
            tabelaNutricional.setValueAt(pratoInfo.getEnergia(), 0, 1);
            tabelaNutricional.setValueAt(pratoInfo.getProteina(), 1, 1);
            tabelaNutricional.setValueAt(pratoInfo.getLipidos(), 2, 1);
            tabelaNutricional.setValueAt(pratoInfo.getColestrol(), 3, 1);
            tabelaNutricional.setValueAt(pratoInfo.getHidratos(), 4, 1);
            tabelaNutricional.setValueAt(pratoInfo.getFibra(), 5, 1);
        } catch (SQLException ex) {
            Logger.getLogger(TabelaNutricional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDoPrato = new javax.swing.JLabel();
        cozinhaPrato = new javax.swing.JLabel();
        dosesPrato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNutricional = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeDoPrato.setText("Nome do Prato: ");

        cozinhaPrato.setText("Tipo de Cozinha:");

        dosesPrato.setText("Doses: ");

        tabelaNutricional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Energia (kcal)", null},
                {"Proteinas (g)", null},
                {"Lipidos (g)", null},
                {"Colestrol (mg)", null},
                {"Hidratos de Caborno (g)", null},
                {"Fibra Alimentar (g)", null}
            },
            new String [] {
                "Propriedades", "Para N Doses"
            }
        ));
        jScrollPane1.setViewportView(tabelaNutricional);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosesPrato)
                    .addComponent(cozinhaPrato)
                    .addComponent(nomeDoPrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nomeDoPrato)
                .addGap(18, 18, 18)
                .addComponent(cozinhaPrato)
                .addGap(18, 18, 18)
                .addComponent(dosesPrato)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaNutricional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaNutricional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaNutricional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaNutricional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaNutricional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cozinhaPrato;
    private javax.swing.JLabel dosesPrato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeDoPrato;
    private javax.swing.JTable tabelaNutricional;
    // End of variables declaration//GEN-END:variables

}
